### ISSUE TITLE
Move this repo to your github user

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-checkstyle-formatter#2]
@davidtheclark SuitCSS, CSS Recipes and Wordpress configs are moved.

I think it's [easier](https://help.github.com/articles/transferring-a-repository/#transferring-from-an-organization-to-a-user) if you, rather than I, trigger the move of this repo. Does that sound OK with you?

**Comment by davidtheclark** [comment]
Done.

**Comment by jeddy3** [comment]
Thanks!

FYI. I'm away this weekend, but I hope to pick up on a few stylelint issues next week :)
