### ISSUE TITLE
How do I run stylelint with this formatter?

### ISSUE THREAD

**Issue by znerd** [stylelint/stylelint-checkstyle-formatter#6]
How can I run `stylelint` with this formatter?

I tried various this (and various similar forms):

```
stylelint * --formatter checkstyle
```

…but that obviously is not the right approach.

**Comment by davidtheclark** [comment]
You should use the `--custom-formatter` option, and stylelint asks for a path to the custom formatter module. In this case, probably `--custom-formatter=node_modules/stylelint-checkstyle-formatter`.

**Comment by znerd** [comment]
That works indeed. Thanks a lot !
